server:
  port: 8888

spring:
  profiles:
    active: native, git
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/nhavronskyi/Documents/git/spotik/spotik-config-service/src/main/resources/config
        git:
          uri: https://github.com/nhavronskyi/property-files.git
          username: nhavronskyi
          password: ${git_token}