server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nhavronskyi/property-files.git
          username: nhavronskyi
          password: ${git_token}