server:
  port: 8888

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///Users/nhavronskyi/Documents/git/spotik/spotik-config-service/src/main/resources/config