server:
  port: 8888

spring:
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: ${uri_to_folder}
          username: ${git_username}
          password: ${git_token}
